// Code generated by mockery v2.9.4. DO NOT EDIT.

package backend

import (
	context "context"

	core "github.com/cschleiden/go-dt/pkg/core"
	history "github.com/cschleiden/go-dt/pkg/history"

	mock "github.com/stretchr/testify/mock"

	task "github.com/cschleiden/go-dt/pkg/core/task"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

// CompleteActivityTask provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockBackend) CompleteActivityTask(_a0 context.Context, _a1 core.WorkflowInstance, _a2 string, _a3 history.HistoryEvent) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.WorkflowInstance, string, history.HistoryEvent) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteWorkflowTask provides a mock function with given fields: ctx, _a1, newEvents, workflowMessages
func (_m *MockBackend) CompleteWorkflowTask(ctx context.Context, _a1 task.Workflow, newEvents []history.HistoryEvent, workflowMessages []core.TaskMessage) error {
	ret := _m.Called(ctx, _a1, newEvents, workflowMessages)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, task.Workflow, []history.HistoryEvent, []core.TaskMessage) error); ok {
		r0 = rf(ctx, _a1, newEvents, workflowMessages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWorkflowInstance provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) CreateWorkflowInstance(_a0 context.Context, _a1 core.TaskMessage) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.TaskMessage) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActivityTask provides a mock function with given fields: _a0
func (_m *MockBackend) GetActivityTask(_a0 context.Context) (*task.Activity, error) {
	ret := _m.Called(_a0)

	var r0 *task.Activity
	if rf, ok := ret.Get(0).(func(context.Context) *task.Activity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Activity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkflowTask provides a mock function with given fields: _a0
func (_m *MockBackend) GetWorkflowTask(_a0 context.Context) (*task.Workflow, error) {
	ret := _m.Called(_a0)

	var r0 *task.Workflow
	if rf, ok := ret.Get(0).(func(context.Context) *task.Workflow); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Workflow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignalWorkflow provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockBackend) SignalWorkflow(_a0 context.Context, _a1 core.WorkflowInstance, _a2 history.HistoryEvent) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.WorkflowInstance, history.HistoryEvent) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
