version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - bidichk
    - bodyclose
    - errcheck
    - errname
    - errorlint
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - staticcheck
    - tagalign
    - testifylint
    - tparallel
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
    - unused
    - goworkflows
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1003"
    custom:
      goworkflows:
        type: "module"
        original-url: "github.com/cschleiden/go-workflows/analyzer"
        settings:
          checkprivatereturnvalues: true


formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - "github.com/cschleiden/go-workflows"
