run:
  tests: false

linters:
  enable:
  - goworkflows

linters-settings:
  custom:
    goworkflows:
      path: ./plugin.so
      description: go-workflows
      original-url: github.com/cschleiden/go-workflows/analyzer