version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - bidichk
    - bodyclose
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - staticcheck
    - tagalign
    - testifylint
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - unused
    # - goworkflows
  disable:
    - errname
    - errcheck
    - errorlint
    - usetesting
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1012"
        - "-ST1020"
        - "-SA5010"
    # custom:
    #   goworkflows:
    #     type: "module"
    #     original-url: "github.com/cschleiden/go-workflows/analyzer"
    #     settings:
    #       checkprivatereturnvalues: true


formatters:
  enable:
    - gofmt
    # - goimports
  settings:
    goimports:
      local-prefixes:
        - "github.com/cschleiden/go-workflows"
