version: '3.1'

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --appendfsync always --loglevel warning --requirepass RedisPassw0rd
    volumes:
      - cache:/data

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

volumes:
  cache:
    driver: local
